### ISSUE TITLE
Util hooks trouble with multiplayer

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#32]
Loading a multiplayer lobby crashes.

Disabling `jmpPatch(InitializeDialogWrapper, 0x00419D20, 1);` seems to fix this behaviour.

**Comment by BoomerangAide** [comment]
Will fix it in the next version.
The fix is to remove "static" for the stack_placeholder structure.
The same can be applied to the similar struct in buttonsets.cpp (maybe there's less risk with that one, but I will do it to be sure).

What happened is that at some point in call A of InitializeDialog , within the second call to fxnInteract the InitializeDialog function would be called again, and this call B would overwrite the structure used by A (since all InitializeDialog shared the same static structure), and after B would return, A would use the wrong structure (the one from B) for the 3rd call to fxnInteract.
I hope it's not too confusing.

**Comment by BoomerangAide** [comment]
Fixed in Version 4.102
