### ISSUE TITLE
Cancelling research crashes the game when Cancel Research hook is enabled

### ISSUE THREAD

**Issue by Voyager7456** [BoomerangAide/GPTP-For-VS2008#34]
When CMDRECV_CancelResearch is hooked, the game crashes when you cancel research. I am using the unmodified 4.014 hook.

**Comment by BoomerangAide** [comment]
Fixed in Version 4.105.
I must have been tired to make the helper using the address of the calling function, both in name and value, and not realize it.
Well, it was the first time the error file of Starcraft made the problem so obvious (even the unusually big file size was a clue).

Thank you for reporting the issue.
