### ISSUE TITLE
Miscellaneous (Questions & Request)

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#9]
[22/08/2015]:

> Hi!.
> 
> Maybe you could work on the screen size.
> Right now, SC engine only renders a 640px400p image:
> http://www.moddb.com/members/kysxd/images/weird
> 
> Could you find a way to make the game render a fully 640x480??
> 
> Edit: Is there a way to resize the game layer from 640X400 to 640x480 (and also, resize the dialog layer to avoid conflicts)??
> 
> Also, could you make more than 1 building selectable?
> (And maybe after that, look for +12 units selection).
> 
> Greetings.

[18/09/2015]:

> Hi!. Some questions/request.
> 
> There are some hooks for the AI on spells.
> Any chance to make one for the harvest behavior (AI)?
> 
> Where can i modify the larva amount for buildings?
> I want to make the Hatchery, Lair and Hive to spawn 3,4 and 5 larva.
> 
> I know there is an example of how to copy a button set.
> Could you make and example of how to change the buttonset of a unit for a custom one?
> 
> Where is controlled the orderQueueTimer ?
> 
> Also, is possible to re-write the pathfinding?
> 
> Thank you.

**Comment by BoomerangAide** [comment]
Old comment copy:
Hi,

~~First I want to say that this issue is about "hooks", not about implementing new features not existing in Starcraft.
Having a hook allow to change Starcraft behavior around it, but it may take lots of them for some features.~~

About your image, the image size is 640x480, and the minimap display show that Starcraft do display stuff at the bottom.
My guess is that you're trying to draw on the "game" layer stuff that belong to the "dialog" layer (layers are in structures\Layer.h), and that got Starcraft confused, especially since it's normally keeping those as nicely separated rectangles, and you're mixing those 2.
I don't think I can help on that, I already had to find when to stop for the buttonset hook because lots of drawing/interaction functions were too complicated (lots of calls, access to unidentified areas of memory, weird maths...) to be make into hooks, and what you need is probably even more complicated.

For selection, I will have a look to see if I can get hooks for it.
Maybe it will be simple enough that removing something that exclude buildings from multi-selection would work for it.

+12 units selection is harder, since it (clientSelectionGroup) is using a hard-coded array.
Besides, it would require something not existing to view units beyond 12 (or another limit if Starcraft can actually make units wireframes smaller in selection view).

**Comment by BoomerangAide** [comment]
Now, for more recent stuff:

**screen size:** I'm not planning to work on this (and a 640*560 game would probably look weird).Maybe the people who tried to develop stuff like Starcraft HD or Starcraft Windowed Mode could help better than me on this field.

**selection:** Soon, I will upload the selection hooks I've been developing for the past weeks.When they come out, just commenting sections with condition unit_IsStandardAndMovable function would allow to wildly select buildings in groups.It will be enough to show how Starcraft handle that (hint: doesn't crash, but probably not what you want either), and it can be a starting point to create a mod that could, for example, allow to select and use several "factory" type buildings at the same time, but it will require working with new buttonsets (good thing those hooks are already there).

As for +12 selections, there are more than 1 array of selection, and functions have several way of parsing them, using an index (never for the default array T_T), or using the 1st, last and "after last" elements of array as key points (extremely annoying behavior).
To change that with hooks system, new arrays (with constant size) would have to be defined, and all previously behavior would have to be patched to use them, meaning they would have to be hunted in at least 78 functions (those are the ones I counted using array elements offsets, but I could have missed some whose only visible point is the hardcoded 0C (12), since 12 is too common a value to be hunted around.
So this is not something I will be able to handle with hooks.

**AI behavior:** I'm not going to look for hooks on this topic for now.Actually, I'm not even sure the existing hooks work properly (I feel like the AI is acting differently in campaign, like Overlords being more sticky in the first Protoss mission of Brood War), and this would be something I would have to verify before trying to add new stuff.

**Larva amount for buildings:** Based on Firegraft EXE edits, 0x004EA7ED contains the number of larva beyond which spawn stop, and 0x004E8CA5 the maximum amount of larva counted per building (perhaps both for checking for spawn and selection through the main Zerg Building).
The following code executed once somehow should work:
    u8 newLarvaCount = 4; //or another value of your choice
    memoryPatch(0x004EA7ED, &newLarvaCount , 1);
    memoryPatch(0x004E8CA5, &newLarvaCount , 1);
If you meant a different amount of larvas for each different building, that would require more than a patch, but the functions containing those values are unreferenced, so they're not the easiest to make hooks from.

**Custom button set:** If by "custom" you mean one made by Firegraft, I'm not sure that's possible, it's allocated outside of normal Starcraft memory, so it's harder to work with than the constant stuff of normal Starcraft.
If that's not what you meant, I'm not sure how to answer. Copying an entire buttonset allow to have a working start, but you can adjust things after that before getCustomButtonSet return, or even rewrite it completely to manually create buttons with all their properties 1 by 1.
Example: for multi-selected "factory buildings", one stuff to do will probably involve creating a buttonset copying the normal factory buttonset, but then changing the actFunc for the buttons to point on a custom function that will call the normal actFunc for each building of the selection.
Same thing with reqFunc, with the added difficulty that each building may give different result (0, 1, or -1), so the custom function would be more tricky.

**orderQueueTimer:** depend on the unit.To my knowledge, a beacon creating a flag or zerglings have a special case of changing the value of this. Others probably change it in a big pre-action function (I think there are at least 2 of those).
But a few special cases aside, this value is just looping around, so it doesn't need a hook to be manipulated I think.

**pathfinding:** probably on a similar level as +12 selections and graphics, it's beyond my level.Too many functions all around the place.

**Comment by BoomerangAide** [comment]
I made a hook for larvas spawn.
There are unidentified functions around, but it should not get in the way of what you wanted to do.
It is in Update 3.

**Comment by KYSXD** [comment]
Very useful hook, works very well for a different [larva amount](http://www.moddb.com/mods/starcraft-v/videos/scv-test-006).

**Comment by BoomerangAide** [comment]
I don't know how BinEdit work.
I've seen that it should be a dialog editor, so maybe it's able to edit the right area of the console to make space for more than 9 buttons.
After that, I guess an edit would be needed in what I called function_4591D0() (and/or some subfunctions of it) to display buttons according to the new layout, but last time I tried to hook this stuff it was a big failure.
As for "adding a new button with binedit", I'm not sure what it means since I don't know the program. I'm not sure the "dialog" side of the button would be that significant though.

**Comment by KYSXD** [comment]
Any chance to...

-add a creep's range control? (In order to give different range to different buildings)
::Edit:: If isn't possible to give different ranges, is possible to change the max range in GPTP (not directly using firegraft's exe edit)?

-add an "Unload all before die" hook from the bunker?
::Edit:: I mean, to know/control how the bunker keeps alive the inside-units after death, unlike the transports.
-add "Load/Unload" hook?

-control/know how the workers choose the return cargo building?

::Edit::
-Is possible to add a "Ping" hook?

-Doesn't "radio free zerg" count as a cheat flag? (Maybe it should be on enumerations.h)
-Maybe for the unused/unknown cheat codes, you could take a look to the [StarCraft Beta Debug mode](https://www.youtube.com/watch?v=kWEE_b8Xduo) (maybe you already saw that video)

Also:
Replay codes could be analized to know more about Starcraft. These only work (as said) while viewing replays:

/replay show kills ----> Shows the number of kills.
/replay show razings ----> Shows the number of razings.
/replay show slaughter ----> Shows the slaughter leaderboard.
/replay show resources ----> Shows the resources.
/replay show minerals ----> Shows the minerals.
/replay show gas ----> Shows the gas.
/replay show score ----> Shows the total score.
/replay show score units ----> Shows the units score.
/replay show score buildings ----> Shows the buildings score.
/replay show score kills ----> Shows the kills score.
/replay show score razings ----> Shows the razings score.
/replay show score user ----> Shows the custom score.
/replay hide ----> Hides the leaderboard. 

And... btw, thanks for your work and effort.

**Comment by BoomerangAide** [comment]
-creep range control: unlikely (I could not even understand what function_00414680 return, and the fact that it use UnitId::ZergHive as a parameter instead of the unit id is not a good sign).
-Unload all before die: maybe in weapon_damage.cpp, order it to unload all and damage it so that it has only 1 hp left, so it would be killed by fire on the next frame after unloading...maybe that would work?
-Load/Unload hook: planned, but got delayed.Don't remember in details what were the difficulties, may be related to the fact that some actions (unload) are made out of the main game layer.
-Control/Know return cargo building: had a look just now, and it seems hard (unreferenced functions, use of unknown memory addresses).
But while knowledge is hard, control may just be easier, maybe you can just catch workers doing a return_cargo order in game_hooks.cpp, and change their destination using your own method of selection.

**Comment by KYSXD** [comment]
_Edit:_
In scbwdata.h there are first nodes for some of the linked lists (like visible units, hidden, bullets, etc.), but the CUnitLayout includes harvest_link and hangar_link (and burrow_link).

Any advice on how they works?

Why isn't firstBurrowedUnit in scbwdata.h (from cloack_nearby_units.cpp)?
~~It's possible to add "firstHangarUnit" and/or "firstHarvest" ("first_X_unit" in general?)~~

_Edit2:_
~~You should take a look on [BWAPI's CUnit structure](https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BW/CUnit.h), it seems that there are some updates you could make.~~

**Comment by BoomerangAide** [comment]
For the lists, there's a true list of units somewhere, something like CUnit list_of_all_units[MAX_UNITS_COUNT]), and others lists are usually CUnit\* list_of_all_units[LIST_SIZE], where LIST_SIZE can be any value lower or equal to MAX_UNITS_COUNT.
This allow those lists to sort units differently for faster search, and to allocate all units slots from the start to not get "out of memory" error on units creation.

CLink<CUnit> list parameter is equivalent to having 2 parameters: CUnit\* previous_of_list and CUnit\* next_of_list.
Since every unit carry a link to the previous and next unit, from any unit sharing a property (related to hanger, harvest, burrow or other), it's possible to access all the others by always selecting the previous of the previous and the next of the next until reaching NULL, while not allocating any space for a normal list (though it's not exclusive, there can be a real list at the same time).
The first node global node is there in case there's a need to access all those units without having an unit in particular as a starting point.

For firstBurrowedUnit, I guess that's because the only access I made to that file until now was for compatibility with VS 2008. Indeed it should probably be moved to scbwdata.h
I'm currently bug hunting, I'm not in this area currently, but when I reach it, I will check what the game code is doing to understand why it was made this way, and maybe improve it.

For firstHangarUnit, interceptors/scarabs are tied to a single other unit, it doesn't make sense to have a global variable.The "first_X_unit" can be access by unit->interceptor.parent->carrier.inHangarChild and unit->interceptor.parent->carrier.outHangarChild
I think harvest_link is the same, tied to a refinery instead of a carrier/reaver (I'm not sure it's used at all with mineral fields).
Finally, psi_link is probably a link to the pylon too, rather than a link to a global list.

For BWAPI CUnit structure, it's not necessarily more recent than our version of CUnit, and it's designed quite differently since it's not used the same way (read-only and rarely used directly by end-users).
I already made updates at some point, but beyond that, it would be a style-change rather than an upgrade (at some point, I thought it would be possible to have CBuilding, CWorker,CResource and so on, to get rid of unions, but that seems overkill and making the filesize of the GPTP project increase without necessarily making it easier to use).

I had several "come back, delete and rewrite" moments while writing this comment, I hope it does manage to be helpful in the end.

**Comment by KYSXD** [comment]
Hi!
Merry chirstmas and happy new year!

Any chance to create a "place_building" and "place_nydusCanalExit" hooks?
These in order to control the unitId of the unit to place, let more buildings to build (different from nydus canal) and control placing requirements (Like placing non-zerg buildings on creep (personal request, to let my warpgate plugin place protoss buildings on creep) without the zerg flag)

**Comment by BoomerangAide** [comment]
Hi,

Currently looking around this.Is a bit complicated (there's the "place building mode", the order of the builder, the order of the built unit, and maybe more), but I'm trying to move forward.
Don't know if it still work outside of their context, but in the "place building mode" (*IS_PLACING_BUILDING != 0), it seems you could use "u16* const builtUnitIdRef = (u16*)0x0064088A;" to manipulate the id of what's being built (*builtUnitIdRef = wantedId), and "Bool8* const canBuildCheck = (Bool8*)0x006D5BE4;" to decide if the current placement is valid (*canBuildCheck=1).
That's what it look like at my current level of research (maybe I will be proven wrong as I advance in that research, the risk still exist at this time), maybe it become invalid out of the functions where I saw this, or maybe modifying it in the loop of game_hooks.cpp would be too soon or too late to have an effect, but might be worth trying.

edit: started a new branch where I put some of the hooks I got for that research.May not be enough for everything you want to do, but that's a start.Not sure if everything fit in the same file/folder, but I'm putting it on another branch so I can change all that later if needed.

edit2: about units_dat[2], may be SubUnit2 (on my offline file, I added as comment names I found in EUDDB), but I see it called nowhere in Starcraft functions I have, and the corresponding array is completely filled with E400 (UnitId::None), so it's really unused/unimplemented I think.

**Comment by KYSXD** [comment]
That's so cool. Right now I'm testing that hook.

By the way, is the units_dat struct near to be completed?. I'm wondering if the units_dat[2] is the unused (or never implemented) subunit2.

~~Also, got this from a friend, maybe it helps in the research about bunker hooks: (unload units related)
https://pastebin.mozilla.org/8858145 (1 month link).~~

**Comment by BoomerangAide** [comment]
With the addition of function 00473FB0 to the temporary branch, I think you should have the level of control you wanted on building placement.I think this function returning 0 probably always allow a building to be placed (though the others functions may need modding to not display red squares while in building placement mode, since they redo their own calculations, but that would only be visual and not prevent clicking to place the building)

**Comment by KYSXD** [comment]
With the last update (march/25) the nydus rally point plugin was heavily improved, thanks!

~~I was thinking about some stuff:
-Is there any chance to found where the bitmap of the game layer is loaded/called?
With my tests, i found that game layer's pSurface is always NULL(the bitmaps of other layers aren't), at least on gameOn and nextFrame functions.~~

-Any chance to know how SC handles the user interaction? I mean: What happens when the user queues an order? How SC orders all units in clientSelectionGroup to follow the given order?

-Any chance to add a CreateUnitWithProperties function to api.cpp?

**Comment by BoomerangAide** [comment]
-Maybe the game layer is the full 640x480 gameScreenBuffer, and the others layers have their own bitmap because they're drawing over it?
-There are referenced functions starting with CMDACT_ or CMDRECV_or BTNSACT_ that may be the answer of those questions, but soon after they call something like the referenced function QueueGameCommand, I lose track of where the data went and how they are used, so I had to keep it for later.
-I once tried that, but the properties (of StarEdit) were encoded in a way I couldn't translate.I do plan to try again some kind of hook on a CreateUnit function some day, but as can be seen with the CreateUnit in larva_creep_spawn.cpp, those functions are incomplete, and rely on others (function_004A01F0,updateUnitStrength,others...) to finish the stuff, and that's why it's delayed.

**Comment by KYSXD** [comment]
Any chance to add the functions

void showDialog(BinDlg* dialog);		/*0x004186A0*/
void updateDialog(BinDlg* dialog);		/*0x0041C400*/

To the buttonsets hook?

**Comment by BoomerangAide** [comment]
This function is for all dialogs, not just buttonsets.
I tried to make it available, but I failed at implementing "call dword ptr [StarCraft.exe+FE360]" properly, and because of that, the game crashes on startup (since the menus on the first screen are dialogs too).
